require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'IgniteTrivia' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'IgniteTriviaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.78.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'IgniteTrivia-tvOS' do
  # Pods for IgniteTrivia-tvOS

  target 'IgniteTrivia-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
